//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deployer.Lumia.Gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deployer.Lumia.Gui.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WOA Deployer for Lumia v{0}.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to install the GPU. Please, ensure that WOA is installed..
        /// </summary>
        public static string CannotInstallGpu {
            get {
                return ResourceManager.GetString("CannotInstallGpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The drivers have been injected correctly.
        /// </summary>
        public static string DriversInjectedSucessfully {
            get {
                return ResourceManager.GetString("DriversInjectedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual Boot Disabled!.
        /// </summary>
        public static string DualBootDisabled {
            get {
                return ResourceManager.GetString("DualBootDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual Boot Enabled!.
        /// </summary>
        public static string DualBootEnabled {
            get {
                return ResourceManager.GetString("DualBootEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Final steps
        ///
        ///In order to finish the installation, you need to perform these steps manually.
        ///
        ///* Reboot into Windows 10.
        ///* Go to the **Device Manager**
        ///* Under **Unknown Devices**, look for for one described as **&apos;ACPI\MSHW1004\0
        ///&apos;** 
        ///  * **[Tip]** open each one by double clicking on them and look into the **Details** tab for this identifier. It should be one of the first 10 elements of the list.
        ///  * Once you find it choose to *Update* it. 
        ///  * In the driver update wizard, select &quot;Choose driver fr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InstallGpuManualSteps {
            get {
                return ResourceManager.GetString("InstallGpuManualSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid WIM file.
        /// </summary>
        public static string InvalidWimFile {
            get {
                return ResourceManager.GetString("InvalidWimFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual steps.
        /// </summary>
        public static string ManualStepsTitle {
            get {
                return ResourceManager.GetString("ManualStepsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there are no post-OOBE drivers available to inject.
        ///The Core Package that is currently installed doesn&apos;t have an additional post-OOBE driver set..
        /// </summary>
        public static string NoPostOobeDrivers {
            get {
                return ResourceManager.GetString("NoPostOobeDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone is not a Lumia 950 XL.
        /// </summary>
        public static string PhoneIsNotLumia950XL {
            get {
                return ResourceManager.GetString("PhoneIsNotLumia950XL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer Notice and Terms of Use.
        /// </summary>
        public static string TermsOfUseTitle {
            get {
                return ResourceManager.GetString("TermsOfUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - This tool comes with no warranty. 
        ///- The authors can&apos;t be hold responsible for any damage it may cause to your device.    
        ///- This tool intended for usage with Lumia 950 and 950 XL **ONLY**.
        ///    
        ///By clicking &quot;OK&quot; you accept the aforementioned risks..
        /// </summary>
        public static string WarningNotice {
            get {
                return ResourceManager.GetString("WarningNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected .WIM file doesn&apos;t contain any image for ARM64. Please, select a .wim file that targets this architecture..
        /// </summary>
        public static string WimFileNoValidArchitecture {
            get {
                return ResourceManager.GetString("WimFileNoValidArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIM files.
        /// </summary>
        public static string WimFilesFilter {
            get {
                return ResourceManager.GetString("WimFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!
        ///Now, please, **eject the Phone safely** to avoid data corruption issues and reboot your Phone.
        ///After reboot, choose &quot;Windows 10&quot; in the Boot Menu to start the Windows 10 ARM Setup.
        ///Enjoy!.
        /// </summary>
        public static string WindowsDeployedSuccessfully {
            get {
                return ResourceManager.GetString("WindowsDeployedSuccessfully", resourceCulture);
            }
        }
    }
}
